apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello
  namespace: plop
spec:
  suspend: false
  schedule: "*/3 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster; sleep 120
          restartPolicy: OnFailure
