apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-ns-suspender-testing
  labels:
    app: kube-ns-suspender
  namespace: kube-ns-suspender-testing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-ns-suspender
  template:
    metadata:
      labels:
        app: kube-ns-suspender
    spec:
      serviceAccountName: kube-ns-suspender
      containers:
      - name: kube-ns-suspender
        image: ghcr.io/govirtuo/kube-ns-suspender