apiVersion: apps/v1
kind: Deployment
metadata:
  name: misc-depl
  namespace: plop
  labels:
    app: misc
  annotations:
    kube-ns-suspender/originalReplicas: "3"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: misc
  template:
    metadata:
      labels:
        app: misc
    spec:
      containers:
      - name: misc
        image: nginx:latest
        ports:
        - containerPort: 80
