name: "E2E k8s testing"

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  kind:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: engineerd/setup-kind@v0.5.0
        with :
          version: "v0.11.1"
          config: "./tests/config/kind-config.yaml"

      - name: Setup Testing
        run: ./tests/setup.sh        
      - name: Testing
        run: time bats ./tests/detik.sh
      
      - name: Collect logs
        run: |
          echo "---> DETIK logs"
          cp -va /tmp/detik tmp/
          echo "---> KIND logs"
          mkdir -vp tmp/kind
          kind export logs tmp/kind/

      - name: Archive test logs
        uses: actions/upload-artifact@v3
        with:
          name: tests-logs
          path: tmp/
          retention-days: 5
