name: "E2E k8s testing"
on: [pull_request, push]

jobs:
  kind:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: engineerd/setup-kind@v0.5.0
        with :
          version: "v0.11.1"
      - name: Testing
        run: |
          ./tests/setup.sh
          kubectl create ns kube-ns-suspender-testing
          time bats ./tests/detik.sh
