name: "E2E k8s testing"

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  kind:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: engineerd/setup-kind@v0.5.0
        with :
          version: "v0.11.1"
          config: "./tests/config/kind-config.yaml"
      - name: Testing
        run: |
          ./tests/setup.sh
          time bats ./tests/detik.sh
